In [20]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [21]:
yt_df = pd.read_csv('USvideos.csv', parse_dates=['publish_time'])

In [22]:
yt_df['trending_date'] = pd.to_datetime(yt_df['trending_date'], format="%y.%d.%m")

In [23]:
yt_df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,2kyS6SvSYSE,2017-11-14,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13 17:13:01+00:00,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,2017-11-14,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13 07:30:00+00:00,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,2017-11-14,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13 11:00:04+00:00,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...

In [24]:
yt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40949 entries, 0 to 40948
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                40949 non-null  object
 1   trending_date           40949 non-null  datetime64[ns]
 2   title                   40949 non-null  object
 3   channel_title           40949 non-null  object
 4   category_id             40949 non-null  int64
 5   publish_time            40949 non-null  datetime64[ns, UTC]
 6   tags                    40949 non-null  object
 7   views                   40949 non-null  int64
 8   likes                   40949 non-null  int64
 9   dislikes                40949 non-null  int64
 10  comment_count           40949 non-null  int64
 11  thumbnail_link          40949 non-null  object
 12  comments_disabled       40949 non-null  bool
 13  ratings_disabled        40949 non-null  bool
 14  video_error_or_removed  40949 non-null  bool
 15  description             40379 non-null  object
dtypes: bool(3), datetime64[ns, UTC](1), datetime64[ns](1), int64(5), object(6)
memory usage: 4.2+ MB

In [25]:
yt_df.describe()

,trending_date,category_id,views,likes,dislikes,comment_count
count,40949,40949.000000,4.094900e+04,4.094900e+04,4.094900e+04,4.094900e+04
mean,2018-02-27 06:22:42.494810624,19.972429,2.360785e+06,7.426670e+04,3.711401e+03,8.446804e+03
min,2017-11-14 00:00:00,1.000000,5.490000e+02,0.000000e+00,0.000000e+00,0.000000e+00
25%,2018-01-04 00:00:00,17.000000,2.423290e+05,5.424000e+03,2.020000e+02,6.140000e+02
50%,2018-02-26 00:00:00,24.000000,6.818610e+05,1.809100e+04,6.310000e+02,1.856000e+03
75%,2018-04-24 00:00:00,25.000000,1.823157e+06,5.541700e+04,1.938000e+03,5.755000e+03
max,2018-06-14 00:00:00,43.000000,2.252119e+08,5.613827e+06,1.674420e+06,1.361580e+06
std,NaN,7.568327,7.394114e+06,2.288853e+05,2.902971e+04,3.743049e+04

In [27]:
yt_df.sample(5)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
29541,jlmNwjdYVnk,2018-04-18,Boy Sings Out in Walmart || ViralHog,ViralHog,10,2018-03-26 18:24:47+00:00,viralhog,2029850,34209,2315,6485,https://i.ytimg.com/vi/jlmNwjdYVnk/default.jpg,False,False,False,"Occurred on March 24, 2018 / Harrisburg, Illin..."
25701,WknsomB28mE,2018-03-24,TRYING A DRUGSTORE MAGNETIC MASK! ⚡️,Carli Bybel,26,2018-03-14 14:18:28+00:00,"carli|""bybel""|""drugstore""|""magnetic mask""|""try...",603673,21228,744,1155,https://i.ytimg.com/vi/WknsomB28mE/default.jpg,False,False,False,THUMBS UP FOR MORE FIRST IMPRESSION VIDEOS :) ...
13780,yBXcNcBnImc,2018-01-23,The Most Expensive Countries To Buy Cool Used ...,Car Throttle,2,2018-01-17 19:28:07+00:00,"Carthrottle|""car throttle""|""GT-R""|""Alex Kerste...",277651,8833,194,5592,https://i.ytimg.com/vi/yBXcNcBnImc/default.jpg,False,False,False,The used car market in the UK is one of the be...
8687,OWYKrIKMO1M,2017-12-27,WE HAVE BECOME CHARACTERS IN A GAME!!!!,JOLLY,23,2017-12-22 11:40:25+00:00,"Jolly|""JOLLY""|""jolly""|""졸리""|""조쉬""|""조시""|""올리""|""jos...",184075,5279,120,522,https://i.ytimg.com/vi/OWYKrIKMO1M/default.jpg,False,False,False,Today we find our own Jolly faces in an online...
2405,AxWxJNHoLC8,2017-11-26,What Is Schizophrenia Like?,BuzzFeedVideo,22,2017-11-25 22:00:07+00:00,"buzzfeed|""buzzfeedvideo""|""buzzfeed video""|""sch...",276444,9857,476,1258,https://i.ytimg.com/vi/AxWxJNHoLC8/default.jpg,False,False,False,The only way to learn about schizophrenia is t...

Ideas:
Most popular category ID's,
Best time of the year/month to post (Time of year, Views/Likes)

In [ ]:
#yt_cat_df = pd.read_json("US_category_id.json")

In [42]:
import json

with open("US_category_id.json") as yt_cat:
    data = json.load(yt_cat)

yt_cat_flat = pd.json_normalize(data, record_path="items")

In [44]:
yt_cat_flat.head()

,kind,etag,id,snippet.channelId,snippet.title,snippet.assignable
0,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/Xy1mB4_yLrHy_BmKm...",1,UCBR8-60-B28hp2BmDPdntcQ,Film & Animation,True
1,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/UZ1oLIIz2dxIhO45Z...",2,UCBR8-60-B28hp2BmDPdntcQ,Autos & Vehicles,True
2,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/nqRIq97-xe5XRZTxb...",10,UCBR8-60-B28hp2BmDPdntcQ,Music,True
3,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/HwXKamM1Q20q9BN-o...",15,UCBR8-60-B28hp2BmDPdntcQ,Pets & Animals,True
4,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/9GQMSRjrZdHeb1OEM...",17,UCBR8-60-B28hp2BmDPdntcQ,Sports,True

In [46]:
category_dict = {}

for item in yt_cat_flat['items']:
    cat_id = item['id']
    title = item['snippet']['title']
    print(f"ID: {cat_id} | Title: {title}")

print(category_dict)

KeyError: 'items'